"""add medicine schedule fields

Revision ID: 68493d1a5e07
Revises: eb4f2d5c31d0
Create Date: 2026-06-15 08:26:31.705401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '68493d1a5e07'
down_revision: Union[str, Sequence[str], None] = 'eb4f2d5c31d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine_reminders', sa.Column('morning', sa.Boolean(), nullable=False))
    op.add_column('medicine_reminders', sa.Column('afternoon', sa.Boolean(), nullable=False))
    op.add_column('medicine_reminders', sa.Column('night', sa.Boolean(), nullable=False))
    op.add_column('medicine_reminders', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_column('medicine_reminders', 'reminder_time')
    op.drop_column('medicine_reminders', 'time_slot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine_reminders', sa.Column('time_slot', mysql.VARCHAR(length=30), nullable=False))
    op.add_column('medicine_reminders', sa.Column('reminder_time', mysql.TIME(), nullable=False))
    op.drop_column('medicine_reminders', 'notes')
    op.drop_column('medicine_reminders', 'night')
    op.drop_column('medicine_reminders', 'afternoon')
    op.drop_column('medicine_reminders', 'morning')
    # ### end Alembic commands ###
